apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: virt-observability-controller
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines", "virtualmachineinstances", "virtualmachineinstancemigrations", "kubevirts"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["snapshot.kubevirt.io"]
  resources: ["virtualmachinesnapshots", "virtualmachinerestores"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["export.kubevirt.io"]
  resources: ["virtualmachineexports"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["clone.kubevirt.io"]
  resources: ["virtualmachineclones"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["pool.kubevirt.io"]
  resources: ["virtualmachinepools"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["instancetype.kubevirt.io"]
  resources: ["virtualmachineinstancetypes", "virtualmachineclusterinstancetypes", "virtualmachinepreferences", "virtualmachineclusterpreferences"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["controllerrevisions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
